name: generate_rust

on:
  push:
    branches: [ master ]
    paths:
    - "templates/rust/**"
    - .github/workflows/generate_rust.yml
  pull_request:
    branches: [ master ]
    paths:
    - "templates/rust/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: install wapc
      run: sudo npm install -g git+https://github.com/wapc/cli.git#master
    - name: generate
      run: wapc new rust gen-rust
      working-directory: /tmp
    - name: build from generated template
      run: make
      working-directory: /tmp/gen-rust
    - name: clippy_check
      run: cargo clippy
      working-directory: /tmp/gen-rust

